name: Rotate Dynamic Media Token

on:
  schedule:
    # every 6 hours - token is valid 24 hours
    # this allows for ~3 failures to still rotate within 24h
    # (42m is to be outside any high load times)
    - cron: '42 */6 * * *'
  workflow_dispatch:

jobs:
  rotate:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: cloudflare
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 24
      - run: npm ci
      - name: Rotate token and update secrets
        run: |
          # generate new token
          DM_ACCESS_TOKEN=$(./scripts/create-ims-token.sh "$DM_CLIENT_ID" "$DM_CLIENT_SECRET" "AdobeID,openid")

          # update secrets in cloudflare
          echo "$DM_CLIENT_ID"    | ./scripts/secret-store-update.sh ${{ vars.CLOUDFLARE_SECRET_STORE_ID }} "KOASSETS_DM_CLIENT_ID"
          echo "$DM_ACCESS_TOKEN" | ./scripts/secret-store-update.sh ${{ vars.CLOUDFLARE_SECRET_STORE_ID }} "KOASSETS_DM_ACCESS_TOKEN"
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          DM_CLIENT_ID: ${{ secrets.DM_CLIENT_ID }}
          DM_CLIENT_SECRET: ${{ secrets.DM_CLIENT_SECRET }}
